import { Routes } from '@angular/router';
import { Home } from './home/home';
import { InitSpelers } from './init-spelers/init-spelers';
import { Spelers } from './spelers/spelers';
import { MainMenu } from './main-menu/main-menu';
import { Koppels } from './seizoen/koppels/koppels';
import { KoppelsToevoegen } from './seizoen/koppels/koppels-toevoegen/koppels-toevoegen';
import { KoppelPreferences } from './seizoen/koppels/koppel-preferences/koppel-preferences';
import { Settings } from './seizoen/settings/settings';
import { Rondes } from './seizoen/rondes/rondes';
import { Probeer } from './probeer/probeer';
import { SeizoenMenu } from './seizoen/seizoen-menu/seizoen-menu';
import { PoulesAanmaken } from './seizoen/rondes/poule/planning/poules-aanmaken/poules-aanmaken';
import { PoulesOverview } from './seizoen/rondes/poule/spelen/poules-overview/poules-overview';
import { PouleOverview } from './seizoen/rondes/poule/spelen/poule-overview/poule-overview';
import { PouleSchema } from './seizoen/rondes/poule/spelen/poule-schema/poule-schema';
import { PouleMatch } from './seizoen/rondes/poule/spelen/poule-match/poule-match';
import { PouleWedstrijd } from './seizoen/rondes/poule/spelen/poule-wedstrijd/poule-wedstrijd';
import { PouleScorebord } from './seizoen/rondes/poule/spelen/poule-scorebord/poule-scorebord';
import { PoulesSpeeldagen } from './seizoen/rondes/poule/planning/poules-speeldagen/poules-speeldagen';
import { MatchesAanmakenR2 } from './seizoen/rondes/afval/planning/matches-aanmaken-r2/matches-aanmaken-r2';
import { MatchesAanmaken } from './seizoen/rondes/afval/planning/matches-aanmaken/matches-aanmaken';
import { MatchesSpeeldagenR2 } from './seizoen/rondes/afval/planning/matches-speeldagen-r2/matches-speeldagen-r2';
import { MatchesSpeeldagen } from './seizoen/rondes/afval/planning/matches-speeldagen/matches-speeldagen';
import { RondeKoppels } from './seizoen/rondes/koppels/ronde-koppels/ronde-koppels';
import { RondeKoppelDetail } from './seizoen/rondes/koppels/ronde-koppel-detail/ronde-koppel-detail';

export const routes: Routes = [
    { path: 'home', component: Home },
    { path: 'main', component: MainMenu },
    { path: 'seizoen', component: SeizoenMenu },
    { path: 'settings', component: Settings },
    { path: 'koppels/toevoegen', component: KoppelsToevoegen },
    { path: 'koppels/:koppelId', component: KoppelPreferences },
    { path: 'koppels', component: Koppels },
    { path: 'rondes/poule/:rondeId/spel/:pouleIdx/match/:splKopId/:tegKopId/:wedIdx/score', component: PouleScorebord },
    { path: 'rondes/poule/:rondeId/spel/:pouleIdx/match/:splKopId/:tegKopId/:wedIdx', component: PouleWedstrijd },
    { path: 'rondes/poule/:rondeId/spel/:pouleIdx/match/:splKopId/:tegKopId', component: PouleMatch },
    { path: 'rondes/poule/:rondeId/spel/:pouleIdx/schema', component: PouleSchema },
    { path: 'rondes/poule/:rondeId/spel/:pouleIdx', component: PouleOverview },
    { path: 'rondes/poule/:rondeId/spel', component: PoulesOverview },
    { path: 'rondes/poule/:rondeId/data', component: PoulesSpeeldagen },
    { path: 'rondes/poule/:rondeId/planner', component: PoulesAanmaken },
    { path: 'rondes/afval/2/planner', component: MatchesAanmakenR2 },
    { path: 'rondes/afval/2/data', component: MatchesSpeeldagenR2 },
    { path: 'rondes/afval/:rondeId/planner', component: MatchesAanmaken },
    { path: 'rondes/afval/:rondeId/data', component: MatchesSpeeldagen },
    { path: 'rondes/:rondeId/koppels/:koppelId', component: RondeKoppelDetail },
    { path: 'rondes/:rondeId/koppels', component: RondeKoppels },
    { path: 'rondes', component: Rondes },
    { path: 'init', component: InitSpelers },
    { path: 'spelers', component: Spelers },
    { path: 'probeer', component: Probeer },
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: '**', redirectTo: 'home', pathMatch: 'full' }
];
